import { jsPDF } from 'jspdf'

const PAGE = {
  width: 210,
  height: 297,
  left: 14,
  right: 196,
}

function ensureSpace(doc, y, needed = 24) {
  if (y + needed <= PAGE.height - 12) {
    return y
  }

  doc.addPage()
  return 20
}

function drawHeader(doc, data) {
  doc.setFillColor(79, 70, 229)
  doc.rect(0, 0, PAGE.width, 36, 'F')

  doc.setTextColor(255, 255, 255)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(17)
  doc.text('Skill Gap Analyzer Report', PAGE.left, 14)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.text(`Generated: ${new Date().toLocaleString()}`, PAGE.left, 21)
  doc.text(`Role Focus: ${data.desiredRole ?? '-'}`, PAGE.left, 27)

  doc.setTextColor(30, 41, 59)
  return 44
}

function drawSectionTitle(doc, title, y) {
  y = ensureSpace(doc, y, 12)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(12)
  doc.setTextColor(51, 65, 85)
  doc.text(title, PAGE.left, y)
  doc.setDrawColor(203, 213, 225)
  doc.line(PAGE.left, y + 2, PAGE.right, y + 2)
  doc.setTextColor(30, 41, 59)
  return y + 8
}

function drawKeyValueRows(doc, rows, y) {
  rows.forEach(([label, value]) => {
    y = ensureSpace(doc, y, 8)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(10)
    doc.text(`${label}:`, PAGE.left, y)

    doc.setFont('helvetica', 'normal')
    const wrapped = doc.splitTextToSize(String(value ?? '-'), 130)
    doc.text(wrapped, 62, y)
    y += wrapped.length * 5
  })

  return y + 1
}

function drawBulletList(doc, items, y) {
  const list = items && items.length ? items : ['-']

  list.forEach((item) => {
    y = ensureSpace(doc, y, 8)
    const wrapped = doc.splitTextToSize(String(item), 170)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(10)
    doc.text('•', PAGE.left, y)
    doc.text(wrapped, PAGE.left + 5, y)
    y += wrapped.length * 5
  })

  return y + 1
}

function drawRoleTable(doc, roles, y) {
  const entries = roles && roles.length ? roles : []

  y = ensureSpace(doc, y, 18)

  doc.setFillColor(238, 242, 255)
  doc.rect(PAGE.left, y - 5, PAGE.right - PAGE.left, 8, 'F')
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(10)
  doc.text('Rank', PAGE.left + 2, y)
  doc.text('Role', PAGE.left + 22, y)
  doc.text('Match', PAGE.left + 112, y)
  doc.text('Demand', PAGE.left + 148, y)
  y += 8

  if (!entries.length) {
    doc.setFont('helvetica', 'normal')
    doc.text('No suggested roles available', PAGE.left + 2, y)
    return y + 6
  }

  entries.slice(0, 8).forEach((role, index) => {
    y = ensureSpace(doc, y, 8)
    doc.setDrawColor(226, 232, 240)
    doc.line(PAGE.left, y + 2, PAGE.right, y + 2)

    doc.setFont('helvetica', 'normal')
    doc.text(`#${index + 1}`, PAGE.left + 2, y)
    doc.text(doc.splitTextToSize(String(role.role || '-'), 80), PAGE.left + 22, y)
    doc.text(`${role.match_percentage ?? 0}%`, PAGE.left + 112, y)
    doc.text(String(role.market_demand ?? 0), PAGE.left + 148, y)
    y += 6
  })

  return y + 2
}

export function downloadAnalysisPdf(data) {
  if (!data) return

  const doc = new jsPDF()
  let y = drawHeader(doc, data)

  y = drawSectionTitle(doc, 'Candidate Profile', y)
  y = drawKeyValueRows(
    doc,
    [
      ['Report Owner', data.reportUserName ?? '-'],
      ['Owner Email', data.reportUserEmail ?? '-'],
      ['Desired Role', data.desiredRole ?? '-'],
      ['Student Skills', (data.userSkills || []).join(', ') || '-'],
    ],
    y,
  )

  y = drawSectionTitle(doc, 'Assessment Summary', y)
  y = drawKeyValueRows(
    doc,
    [
      ['Assessment Score', `${data.testScore ?? '-'} / 100`],
      ['Proficiency Level', data.proficiency ?? '-'],
      ['Role Match Score', `${data.roleMatchScore ?? 0}%`],
    ],
    y,
  )

  if (data.careerBand) {
    y = drawSectionTitle(doc, 'Career Band Recommendation', y)
    y = drawKeyValueRows(
      doc,
      [
        ['Company Types', (data.careerBand.companyTypes || []).join(', ') || '-'],
        ['Salary Band', data.careerBand.salaryBandLPA || '-'],
        ['Job Level', data.careerBand.jobLevel || '-'],
        ['Guidance', data.careerBand.guidance || '-'],
      ],
      y,
    )
  }

  y = drawSectionTitle(doc, 'Skills to Learn', y)
  y = drawBulletList(doc, (data.missingSkills || []).length ? data.missingSkills : ['No missing skills'], y)

  y = drawSectionTitle(doc, 'Highly Recommended Skills', y)
  y = drawBulletList(doc, (data.recommendedSkills || []).length ? data.recommendedSkills : ['No additional recommendations'], y)

  y = drawSectionTitle(doc, 'Suggested Career Roles', y)
  y = drawRoleTable(doc, data.suggestedRoles || [], y)

  doc.setFont('helvetica', 'italic')
  doc.setFontSize(9)
  doc.setTextColor(71, 85, 105)
  doc.text('Generated by Skill Gap Analyzer', PAGE.left, PAGE.height - 8)

  const safeRole = String(data.desiredRole || 'report').replace(/\s+/g, '_').toLowerCase()
  doc.save(`skill_gap_report_${safeRole}.pdf`)
}
